# Iris_Class

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris=load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [21]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [22]:
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [23]:
iris.feature_names #컬럼명으로 사용가능

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [24]:
iris['target'] # 품종의 인덱스 번호를 가르킴

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [25]:
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [27]:
iris['data'].shape #150개의 행 4개의 컬럼(문제)
iris['target'].shape #150개(정답)

(150,)

In [44]:
df=pd.DataFrame(iris.data, columns=iris['feature_names'])
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [46]:
target_col_val=[iris['target_names'][t] for t in iris['target']]

df['target']=target_col_val
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

        target  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [4]:
from sklearn.model_selection import train_test_split
#학습용과 검증용 데이터를 분리

In [59]:
X_train,X_test,y_train,y_test=train_test_split(iris['data'], iris['target'],test_size=0.2)
X_train.shape, X_test.shape,y_train.shape,y_test.shape

((120, 4), (30, 4), (120,), (30,))

In [5]:
from sklearn.neighbors import KNeighborsClassifier

In [61]:
knn =KNeighborsClassifier()
knn

KNeighborsClassifier()

In [62]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [63]:
y_pred=knn.predict(X_test)#학습할때 주지  않았던 문제를 준다(test)

In [64]:
y_pred

array([0, 0, 1, 2, 2, 0, 0, 1, 0, 0, 2, 2, 1, 0, 2, 2, 2, 1, 1, 2, 0, 0,
       1, 2, 1, 1, 1, 2, 0, 0])

In [67]:
knn.score(X_test,y_test)

0.9666666666666667

# 데이터 변환

In [6]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()#표준화 해줌(평균은 0 표준 편차는 1로)

In [7]:
scaler.fit_transform(iris['data'])
X = scaler.transform(iris['data']) # 데이터들을 0 중심으로 표준화 해줌

In [8]:
X_train,X_test,y_train,y_test=train_test_split(X, iris['target'],test_size=0.2)

In [9]:
knn =KNeighborsClassifier()

In [10]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [11]:
y_pred=knn.predict(X_test)

In [12]:
y_pred

array([2, 2, 0, 0, 0, 0, 2, 1, 0, 1, 0, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 2,
       0, 1, 1, 0, 2, 1, 1, 1])

In [13]:
knn.score(X_test,y_test)

0.9666666666666667