# 넘파이에서의 데이터 삭제

In [2]:
import numpy as np

arr = np.array([1,2,3,4,5])
arr=np.delete(arr,2)#두번째 자리
arr

array([1, 2, 4, 5])

In [ ]:
#넘파이 create에는 array, arange, zeros,ones, linspace....등이 있음

In [ ]:
arr = np.array(["alice", "bob", "charlie", "david", "eric"])
arr=np.delete(arr,[0,1,2])#다수개를 제거
arr

In [ ]:
arr =np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr=np.delete(arr,1,axis=1)#각행의 첫번째 자리에 있는 값을 세로로 없애기(열을 삭제해라)
arr

In [ ]:
arr =np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr=np.delete(arr,[0,3],axis=1)#다수개를 삭제 (열을 삭제)
arr

In [ ]:
arr =np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr.shape)
arr=np.delete(arr,0,axis=0)#0번째 행을 없앤다
arr

In [ ]:
arr =np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr=np.delete(arr,[0,2],axis=0)#다수개의 행을 삭제
arr

In [44]:
arr= np.array([1,1,1,1,2,3,4,])
arr=np.delete(arr, np.where(arr==1))#where이라는 조건을 줘서 그 조건에 맞는것을 삭제
arr

(array([0, 1, 2, 3], dtype=int64),)


array([2, 3, 4])

# 넘파이 crud

In [129]:
import numpy as np

In [136]:
scorearr=np.zeros([5,3])
numarr=np.array([10,11,12,13,14])
namearr=np.array(["aaa","bbb","ccc","ddd","eee"])
infoarr=np.column_stack((numarr,namearr))
pro=np.hstack((infoarr,scorearr))

class School:
    
    
    
    def emp_list():
        print("--번호--이름---국어--영어---수학")
        print(pro)
        np.load('score.npy')
    def emp_add():
        num=int(input('입력할 번호를 입력하세요'))
        a=np.where(numarr==num)
        stid=a[0][0]
        print(stid)
        score=input('점수를 입력하세여')
        korea,eng,math=score.split()
        pro[stid,2:5]=korea,eng,math
        np.save('score',pro)
            
    def emp_update():
        num=int(input('수정할 번호를 입력하세요'))
        a=np.where(numarr==num)
        stid=a[0][0]
        print(stid)
        score=input('새로점수를 입력하세여')
        korea,eng,math=score.split()
        pro[stid,2:5]=korea,eng,math
        np.save('score',pro)
        
       
        
    def emp_delete():
        num=int(input('찾을 번호를 입력하세요'))
        a= np.where(numarr==11)
        stid=a[0][0]
        print(stid)
        pro=np.delete(pro,stid,axis=0)
        
        
        
        
    def emp_find():
        num=int(input('찾을 번호를 입력하세요'))
        a=np.where(numarr==num)
        stid=a[0][0]
        print(stid)
        print(pro[stid,0:5])
       

In [137]:
mem_dic=[]
m_dic={'s':'LIST', 'f':'FIND', 'a':'ADD', 'u':'UPDATE', 'd':'DELETE', 'x':
       'EXIT'}


def menu():
    print("-----------------------------------------------")
    m=input('목록(s), 검색(f), 추가(a), 수정(u), 삭제(d), 종료(x):')
    return m_dic.get(m)

In [138]:
go = True
while go:
    m=menu()
    if m=='ADD':
        School.emp_add()
    elif m=='LIST':
        School.emp_list()
    elif m=='UPDATE':
        School.emp_update()
    elif m=='DELETE':
        num=int(input('찾을 번호를 입력하세요'))
        a= np.where(numarr==11)
        stid=a[0][0]
        print(stid)
        pro=np.delete(pro,stid,axis=0)
        print(pro)
    elif m=='FIND':
        School.emp_find()
    elif m=='EXIT':
        break
    else:
        print('오류')
        
print('프로그램 종료')  

-----------------------------------------------


목록(s), 검색(f), 추가(a), 수정(u), 삭제(d), 종료(x): a
입력할 번호를 입력하세요 11


1


점수를 입력하세여 ]11 22 33


-----------------------------------------------


목록(s), 검색(f), 추가(a), 수정(u), 삭제(d), 종료(x): s


--번호--이름---국어--영어---수학
-----------------------------------------------


목록(s), 검색(f), 추가(a), 수정(u), 삭제(d), 종료(x): x


프로그램 종료
