In [1]:
import pandas as pd
import numpy as np

In [3]:
s=pd.Series([12,-4,7,9])#1차원 자료구조
s

0    12
1    -4
2     7
3     9
dtype: int64

In [6]:
s=pd.Series([12,-4,7,9],index={'a','b','c','d'})
s

a    12
c    -4
b     7
d     9
dtype: int64

In [7]:
s.index

Index(['a', 'c', 'b', 'd'], dtype='object')

In [10]:
print(s.values)
type(s.values)

[12 -4  7  9]


numpy.ndarray

In [13]:
tmp = s.values[s<0]#조건을 걸어 0보다 작은 value를 가져옴
tmp[0]#값만 갸져오고 싶다면 0번째를 줘야함

-4

In [14]:
s<0#boolean값으로 나옴 인덱스의 값을 불리언으로!

a    False
c     True
b    False
d    False
dtype: bool

In [19]:
print(s[0])
print('----------')
print(s[[0,1]])
print('----------')
print(s[s>0])

12
----------
a    12
c    -4
dtype: int64
----------
a    12
b     7
d     9
dtype: int64


In [24]:
s[[0,1]]= -4 #s의 0번째와 1의 valeu에 -4를 넣자
s

a   -4
c   -4
b    7
d    9
dtype: int64

In [26]:
s['a']=12#다시 a인덱스의 value에 12를 넣어라
s

a    12
c    -4
b     7
d     9
dtype: int64

In [27]:
s[s>0]

a    12
b     7
d     9
dtype: int64

In [29]:
s

a    12
c    -4
b     7
d     9
dtype: int64

In [33]:
s2 = pd.Series(s)
nums=[12,-4,7,9]

In [35]:
s2[0]=100
s,s2,nums
#즉 s2는 s를 가지고 만들었기에 view, 값이 바뀌면 원본인 s도 바뀜

(a    100
 c     -4
 b      7
 d      9
 dtype: int64,
 a    100
 c     -4
 b      7
 d      9
 dtype: int64,
 [12, -4, 7, 9])

In [36]:
# indexer (loc[],ilco[])
# loc[]:lables,boolean
#iloc[]: position integer, boolean

In [37]:
s

a    100
c     -4
b      7
d      9
dtype: int64

In [46]:
s.loc['a']
s.loc[['a','b']]
s.loc[[True,False,False,True]]#ture인 값을 가져옴
s.loc[s>5]

a    100
b      7
d      9
dtype: int64

In [47]:
#iloc[]==인덱스
s.iloc[1]#loc에서는 쓸수 없음


-4

In [50]:
arr = np.arange(5)#배열을 만들어라
arr/2#원소 한개한개를 2로 나눠라

array([0. , 0.5, 1. , 1.5, 2. ])

In [52]:
s=pd.Series(arr*2)
s

0    0
1    2
2    4
3    6
4    8
dtype: int32

In [53]:
s/2#시리즈임

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
dtype: float64

In [56]:
s1 = pd.Series([1,2,3,4])
s2 = pd.Series([5,2,3,4])

s1+s2

0    6
1    4
2    6
3    8
dtype: int64

In [58]:
s1.index=['a','b','c','d']
s1

a    1
b    2
c    3
d    4
dtype: int64

In [59]:
s2.index=['c','d','e','f']
s2

c    5
d    2
e    3
f    4
dtype: int64

In [61]:
s1*s2#인덱스가 다르면 같은 인덱스 끼리만  연산됨
#NaN==>숫자 아님

a     NaN
b     NaN
c    15.0
d     8.0
e     NaN
f     NaN
dtype: float64

In [62]:
s= pd.Series({'a':1,'b':2,'b':3,'c':4,'c':5})#딕션너리 에서 키는 중복되면 안됨
s

a    1
b    3
c    5
dtype: int64

In [68]:
s=pd.Series([1,2,2,4,5],index=['a','b','b','c','c'])#중복 가능
s

a    1
b    2
b    2
c    4
c    5
dtype: int64

In [69]:
s.unique()#중복없이 가져오기

array([1, 2, 4, 5], dtype=int64)

In [72]:
len(s)#배열의 개수
s.value_counts()#통계 어떤값이 몇개가 있는가
#2라는 값은 2개가 있다는 의미


2    2
1    1
4    1
5    1
dtype: int64

In [79]:
s.isin([4])#[]안의 수가 있는지 없는지

a    False
b    False
b    False
c     True
c    False
dtype: bool

# pandas.Series를 이용한 curd


In [79]:
import pandas as pd

subjects = pd.Series(['Java','Spring','Python'])
names = pd.Series(['scott','jone','lora','blake','andy'],index={'a','b','c','d','e'})
stid = pd.Series([11,12,13,14,15],index={'a','b','c','d','e'})
java = pd.Series([0,0,0,0,0],index={'a','b','c','d','e'})
spring = pd.Series([0,0,0,0,0],index={'a','b','c','d','e'})
python = pd.Series([0,0,0,0,0],index={'a','b','c','d','e'})
                

sb=pd.concat((stid,names,java,spring,python),axis=1,)
print(sb)

num=stid.loc[stid==12]
num.index[0]
sb.loc['a'].values


    0      1  2  3  4
a  11  scott  0  0  0
d  12   jone  0  0  0
e  13   lora  0  0  0
b  14  blake  0  0  0
c  15   andy  0  0  0


array([11, 'scott', 0, 0, 0], dtype=object)

In [104]:
m_dic= {'s':'LIST', 'a':'ADD','f':'FIND','u':'UPDATE','d':'DELETE', 'x':'EXIT'}
def menu():
    print('================================================================')
    m = input('목록(s), 추가(a), 검색(번호로 검색, f), 수정(u), 삭제(d), 종료(x):')
    return m_dic.get(m)

In [105]:
def add():
   #* sNum, name = input('번호 이름').split()
    # num = int(sNum.strip())
    # idx = np.where(stid==num)
    # if names[idx]!=name:
    #     print('일치하는 번호와 이름이 없습니다')
    # else:
    #     s1,s2,s3 = input('S1, S2, S3 과목 성적:').split()
    #     score1 = int(s1.strip())
    #     score2 = int(s2.strip())
    #     score3 = int(s3.strip())
    #     scores[idx] = [score1,score2,score3]
    #     np.save('scores', scores)
    #     print('성적입력 성공')
    num=int(input('입력할 번호를 입력하세요'))
        a=stid.loc[stid==num]
        n=num.index[0]
        print(n)
        score=input('점수를 입력하세여')
        korea,eng,math=score.split()
        pro[stid,2:5]=korea,eng,math
        np.save('score',pro)

In [106]:
def list():
    print('================================================================')
    # 컬럼명
    print('번호\t이름', end='')
    for s in subjects:
        print(f'\t{s}', end='')
    print()
    print('--------------------------------------')
    
    # 데이터
    global scores
    try:
        tmp = np.load('scores.npy')
        scores = tmp
    except IOError as ioe:
        pass
    for i in range(len(names)):
        print('{}\t{}\t'.format(stid[i],names[i]), end='')
        for s in scores[i]:
            print('{}\t'.format(s), end='')
        print()

In [107]:
def print_by_index(idx):
    print('================================================================')
    # 컬럼명
    print('번호\t이름', end='')
    for s in subjects:
        print(f'\t{s}', end='')
    print()
    print('--------------------------------------')
    
    num = stid[idx]
    name = names[idx]
    print('{}\t{}\t'.format(num[0],name[0]), end='')
    st_score = scores[idx][0]
    for s in st_score:
        print(f'{s}\t', end='')
    print()
    
    
    

In [108]:
def find():
    sNum = input('학생 번호:')
    num = int(sNum)
    idx = np.where(stid==num)
    print_by_index(idx)

In [109]:
def update():
    tmp = input('학생번호:')
    st_num = int(tmp.strip())
    idx = np.where(stid==st_num)
    
    tmp = input('과목번호(0,1,2) 새 성적:')
    subject_idx, new_score = tmp.strip().split()
    scores[idx, int(subject_idx)] = int(new_score)
    np.save('scores', scores)
    print('--------> 성적 수정 성공')

In [110]:
def delete():
    global stid
    global names
    global scores
    global subjects
    
    tmp = input('학생정보 삭제(0) 과목삭제(1):')
    axis = int(tmp)
    if axis==0:
        tmp = input('삭제할 학생번호:')
        st_num = int(tmp.strip())
        idx = np.where(stid==st_num)
        stid = np.delete(stid, idx)
        names = np.delete(names, idx)
        scores = np.delete(scores, idx, axis=0)
        print('-------------> 학생정보 삭제 성공')
    elif axis==1:
        tmp = input('삭제할 과목번호(0,1,2):')
        idx = int(tmp.strip())
        subjects = np.delete(subjects, idx)
        scores = np.delete(scores, idx, axis=1)
        print('-------------> 과목 삭제 성공')

In [111]:
go = True
while go:
    m = menu()
    if m == 'LIST':
        list()
    elif m=='ADD':
        add()
    elif m=='FIND':
        find()
    elif m=='UPDATE':
        update()
    elif m=='DELETE':
        delete()
    elif m=='EXIT':
        go = False
    else:
        print('--------> 메뉴입력 오류')
        
print('--------> 프로그램 종료')

목록(s), 추가(a), 검색(번호로 검색, f), 수정(u), 삭제(d), 종료(x): a
번호 이름 11 soctt


KeyError: 'key of type tuple not found and not a MultiIndex'