# 데이터 전처리

# 1.merge: 동일한 컬럼,행끼리 합치기(sql의 조인과 같음)

In [ ]:
import numpy as np
import pandas as pd
frame1 = pd.DataFrame( {'id':['ball','pencil','pen','mug','ashtray'],
'price': [12.33,11.44,33.21,13.23,33.62]})

frame1

In [ ]:
frame2 = pd.DataFrame( {'id':['pencil','pencil','ball','pen'],
'color': ['white','red','red','black']})

frame2

In [ ]:
pd.merge(frame1,frame2)#연결조건을 스스로 찾음:(조건이 없을 경우)
#같은 id 컬럼과 그 id의 열로 같은것만 조인

# merge 조건이 있을때

In [ ]:
frame1 = pd.DataFrame( {'id':['ball','pencil','pen','mug','ashtray'],
'color': ['white','red','red','black','green'],
'brand': ['OMG','ABC','ABC','POD','POD']})
frame1

In [ ]:
frame2 = pd.DataFrame( {'id':['pencil','pencil','ball','pen'],
'brand': ['OMG','POD','ABC','POD']})
frame2

In [ ]:
pd.merge(frame1,frame2)

In [ ]:
pd.merge(frame1,frame2,on='id')
#기준이 되는 컬럼은 하나만 나오고 다른 같은 컬럼은 두개 나옴

In [ ]:
pd.merge(frame1,frame2,on='brand')

In [ ]:
frame2.columns = ['sid','brand']
frame2

In [ ]:
pd.merge(frame1, frame2, left_on='id', right_on='sid')

In [ ]:
frame2.columns = ['id','brand']
pd.merge(frame1,frame2,on='id')

# merge(outer)

In [ ]:
pd.merge(frame1,frame2,on='id',how='outer')
#연결 조건에 맞지 않아도 merge 해라

In [ ]:
pd.merge(frame1,frame2,on='id',how='left')
#left outer join

In [ ]:
pd.merge(frame1,frame2,on='id',how='right')
#right outer join

In [ ]:
pd.merge(frame1,frame2,on=['id','brand'],how='outer')

# 인덱스로 merge

In [ ]:
pd.merge(frame1,frame2,right_index=True, left_index=True)

In [ ]:
frame1.join(frame2)#오류
#인덱스를 가지고 join을 하게되면 동일한 컬럼이 있다면 오류가 남

In [ ]:
frame2.columns = ['brand2','id2']
frame1.join(frame2)

# 문제(merge)

In [ ]:
import random
sales1= np.random.randint(1,10,4)

df1 = pd.DataFrame( {'분기':[1,2,3,4], '팀1':sales1})
df1

In [ ]:
sales2= np.random.randint(1,10,4)
df2 = pd.DataFrame( {'분기':[1,2,3,4], '팀2':sales2})
df2

In [ ]:
pd.merge(df1,df2,on='분기',how='outer')

In [ ]:
df1.columns = ['순서','팀1']
df1

In [ ]:
record=pd.merge(df1, df2, left_on='순서', right_on='분기')
record

In [ ]:
record=record.drop(columns=['순서'])
record

In [ ]:
#분기를 인덱스로
record=record.set_index('분기')

In [ ]:
record

In [ ]:
four=record.loc[4]
list(four)

In [ ]:
record.drop(4,axis='rows')

In [ ]:
df1

In [ ]:
df1

In [ ]:
df1=df1.drop(3,axis='rows')

In [ ]:
record=pd.merge(df1,df2,on='분기',how='outer')

In [ ]:
record

In [ ]:
avg=record['팀1'].mean()

record=record.fillna(avg)
record

In [ ]:
df1.columns = ['순서','팀1']
df1

In [ ]:
record=pd.merge(df1, df2, left_on='순서', right_on='분기',how='outer')
record

In [ ]:
df1.set_index('순서')

In [ ]:

df2

In [ ]:
pd.merge(df1,df2,right_index=True, left_index=True)

In [ ]:
df1.join(df2)

In [271]:
df1=df1.reset_index(inplace=True)
df1

AttributeError: 'NoneType' object has no attribute 'reset_index'

In [ ]:
record=pd.merge(df1, df2, left_on='순서', right_on='분기',how='outer')
record

In [ ]:
df1

In [ ]:
record=pd.merge(df1, df2, left_on='순서', right_on='분기',how='outer')
record[record.isnull()]=record['팀1'].mean()
record

In [ ]:
df2

# 다시 처음부터

In [277]:
import random
sales1= np.random.randint(1,10,4)

df1 = pd.DataFrame( {'분기':[1,2,3,4], '팀1':sales1})
df1



분기  팀1
0   1   8
1   2   9
2   3   4
3   4   9

In [242]:
sales2= np.random.randint(1,10,4)
df2 = pd.DataFrame( {'분기':[1,2,3,4], '팀2':sales2})
df2

분기  팀2
0   1   8
1   2   1
2   3   7
3   4   8

In [273]:
df1.columns = ['순서','팀1']

In [265]:
df1=df1.set_index('순서')

In [278]:
df1=df1.drop(3,axis='rows')

In [279]:
df1

분기  팀1
0   1   8
1   2   9
2   3   4

In [252]:
df2

팀2
분기    
1    8
2    1
3    7
4    8

In [281]:
record=pd.merge(df1, df2, left_on='분기', right_index=True)
record

분기  팀1  팀2
0   1   8   8
1   2   9   1
2   3   4   7

# concat(결합)

In [288]:
array1 = np.arange(9).reshape((3,3))
array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [287]:
array2 = np.arange(9).reshape((3,3))+6#각 원소에 6씩 더해라
array2

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [284]:
np.concatenate([array1,array2],axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11],
       [ 6,  7,  8, 12, 13, 14]])

In [286]:
np.concatenate([array1,array2],axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [291]:
ser1 = pd.Series(np.random.rand(4), index=[1,2,3,4])
ser2 = pd.Series(np.random.rand(4), index=[5,6,7,8])
ser1,ser2

(1    0.305783
 2    0.526064
 3    0.660518
 4    0.170881
 dtype: float64,
 5    0.361339
 6    0.430177
 7    0.406152
 8    0.682981
 dtype: float64)

In [290]:
pd.concat([ser1,ser2])

1    0.351598
2    0.756471
3    0.568780
4    0.443799
5    0.932115
6    0.488900
7    0.773678
8    0.961811
dtype: float64

In [292]:
pd.concat([ser1,ser2], axis=1)

0         1
1  0.305783       NaN
2  0.526064       NaN
3  0.660518       NaN
4  0.170881       NaN
5       NaN  0.361339
6       NaN  0.430177
7       NaN  0.406152
8       NaN  0.682981

In [293]:
pd.concat([ser1,ser2], keys=[1,2])#두가지 시리즈를 구분지을 수 있음

1  1    0.305783
   2    0.526064
   3    0.660518
   4    0.170881
2  5    0.361339
   6    0.430177
   7    0.406152
   8    0.682981
dtype: float64

In [294]:
pd.concat([ser1,ser2],axis=1, keys=[1,2])

1         2
1  0.305783       NaN
2  0.526064       NaN
3  0.660518       NaN
4  0.170881       NaN
5       NaN  0.361339
6       NaN  0.430177
7       NaN  0.406152
8       NaN  0.682981

In [295]:
frame1 = pd.DataFrame(np.random.rand(9).reshape(3,3), index=[1,2,3], 
columns=['A','B','C'])

frame2 = pd.DataFrame(np.random.rand(9).reshape(3,3), index=[4,5,6], 
columns=['A','B','C'])

In [296]:
pd.concat([frame1, frame2])

A         B         C
1  0.142614  0.620459  0.229160
2  0.216246  0.503183  0.451619
3  0.113565  0.173852  0.028148
4  0.878348  0.349920  0.688316
5  0.845785  0.051698  0.454470
6  0.597443  0.142872  0.773302

In [297]:
 pd.concat([frame1, frame2], axis=1)

A         B         C         A         B         C
1  0.142614  0.620459  0.229160       NaN       NaN       NaN
2  0.216246  0.503183  0.451619       NaN       NaN       NaN
3  0.113565  0.173852  0.028148       NaN       NaN       NaN
4       NaN       NaN       NaN  0.878348  0.349920  0.688316
5       NaN       NaN       NaN  0.845785  0.051698  0.454470
6       NaN       NaN       NaN  0.597443  0.142872  0.773302

# combining

In [300]:
ser1 = pd.Series(np.random.rand(5),index=[1,2,3,4,5])
ser2 = pd.Series(np.random.rand(4),index=[2,4,5,6])
ser1,ser2

(1    0.241914
 2    0.910603
 3    0.977015
 4    0.437830
 5    0.602344
 dtype: float64,
 2    0.412110
 4    0.687316
 5    0.829669
 6    0.205004
 dtype: float64)

In [301]:
ser1.combine_first(ser2)#겹치는데 어떤걸 살리고 겹칠것인가?


1    0.241914
2    0.910603
3    0.977015
4    0.437830
5    0.602344
6    0.205004
dtype: float64

In [302]:
ser1[:3].combine_first(ser2[:3])
#처음부터 3번째까지는 ser1우선 그 이후에 ser2

1    0.241914
2    0.910603
3    0.977015
4    0.687316
5    0.829669
dtype: float64

# Pivoting(행과 열을 반대로)

In [304]:
frame1 = pd.DataFrame(np.arange(9).reshape(3,3),
index=['white','black','red'],
columns=['ball','pen','pencil'])

frame1

ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [307]:
ser5 = frame1.stack()
ser5

white  ball      0
       pen       1
       pencil    2
black  ball      3
       pen       4
       pencil    5
red    ball      6
       pen       7
       pencil    8
dtype: int32

In [308]:
ser5.unstack()# 다시 원상복구

ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [309]:
ser5.unstack(0)#원래의 인덱스와 컬럼이 바뀐다

white  black  red
ball        0      3    6
pen         1      4    7
pencil      2      5    8

# long, wide format

In [310]:
longframe = pd.DataFrame({ 'color':['white','white','white',
'red','red','red',
'black','black','black'],
'item':['ball','pen','mug',
'ball','pen','mug',
'ball','pen','mug'],
'value': np.random.rand(9)})

longframe

color  item     value
0  white  ball  0.496900
1  white   pen  0.597169
2  white   mug  0.630203
3    red  ball  0.724770
4    red   pen  0.633811
5    red   mug  0.946029
6  black  ball  0.040834
7  black   pen  0.166096
8  black   mug  0.711805

In [311]:
wideframe = longframe.pivot('color','item')
#color이 인덱스가 되고 item이 컬럼이 됨
wideframe

value                    
item       ball       mug       pen
color                              
black  0.040834  0.711805  0.166096
red    0.724770  0.946029  0.633811
white  0.496900  0.630203  0.597169

# removing

In [313]:
frame1 = pd.DataFrame(np.arange(9).reshape(3,3),
index=['white','black','red'],
columns=['ball','pen','pencil'])

frame1

ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [314]:
del frame1['ball']
frame1

pen  pencil
white    1       2
black    4       5
red      7       8

In [315]:
frame1.drop('white')
frame1

pen  pencil
white    1       2
black    4       5
red      7       8

# data transformation
1. 중복데이터 없애기

In [316]:
dframe = pd.DataFrame({ 'color': ['white','white','red','red','white'],
'value': [2,1,3,3,2]})

dframe

color  value
0  white      2
1  white      1
2    red      3
3    red      3
4  white      2

In [318]:
dframe.duplicated()
#중복되는지 아닌지 검사해다오, 앞에 있는것은 
#ok 하지만 뒤에 또 나오면 false

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [319]:
dframe[dframe.duplicated()]
#true인것을 가져옴(즉 중복되는 것)

color  value
3    red      3
4  white      2

In [325]:
dframe=dframe.drop_duplicates()

In [326]:
dframe

color  value
0  white      2
1  white      1
2    red      3

In [328]:
var1= np.random.randint(1,5,10)
var2= np.random.randint(1,5,10)
df1=pd.DataFrame({ 'n1':var1,'n2':var2})


df1

n1  n2
0   2   3
1   3   4
2   3   3
3   3   4
4   4   3
5   3   1
6   3   2
7   3   1
8   2   2
9   2   2

In [329]:
df1.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6    False
7     True
8    False
9     True
dtype: bool

In [330]:
df1=df1.drop_duplicates()
df1

n1  n2
0   2   3
1   3   4
2   3   3
4   4   3
5   3   1
6   3   2
8   2   2

# map

# • replace()—Replaces values

In [332]:
frame = pd.DataFrame({ 'item':['ball','mug','pen','pencil','ashtray'],
'color':['white','rosso','verde','black','yellow'],
'price':[5.56,4.20,1.30,0.56,2.75]})

frame

item   color  price
0     ball   white   5.56
1      mug   rosso   4.20
2      pen   verde   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [333]:
newcolors = {
'rosso': 'red',
'verde': 'green'
}

In [334]:
frame.replace(newcolors)

item   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [335]:
ser = pd.Series([1,3,np.nan,4,6,np.nan,3])
ser

0    1.0
1    3.0
2    NaN
3    4.0
4    6.0
5    NaN
6    3.0
dtype: float64

In [336]:
ser.replace(np.nan,0)

0    1.0
1    3.0
2    0.0
3    4.0
4    6.0
5    0.0
6    3.0
dtype: float64

# 값 추가

In [338]:
frame = pd.DataFrame({ 'item':['ball','mug','pen','pencil','ashtray'],
'color':['white','red','green','black','yellow']})
frame

item   color
0     ball   white
1      mug     red
2      pen   green
3   pencil   black
4  ashtray  yellow

In [339]:
prices = {
'ball' : 5.56,
'mug' : 4.20,
'bottle' : 1.30,
'scissors' : 3.41,
'pen' : 1.30,
'pencil' : 0.56,
'ashtray' : 2.75
}

In [340]:
frame['price'] = frame['item'].map(prices)
frame

item   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

# 이름 바꾸기

In [341]:
frame

item   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [343]:
reindex = {
0: 'first',
1: 'second',
2: 'third',
3: 'fourth',
4: 'fifth'}

In [344]:
frame.rename(reindex)

item   color  price
first      ball   white   5.56
second      mug     red   4.20
third       pen   green   1.30
fourth   pencil   black   0.56
fifth   ashtray  yellow   2.75

In [345]:
recolumn = {
'item':'object',
'price': 'value'}

In [346]:
frame.rename(index=reindex, columns=recolumn)

object   color  value
first      ball   white   5.56
second      mug     red   4.20
third       pen   green   1.30
fourth   pencil   black   0.56
fifth   ashtray  yellow   2.75

In [347]:
frame.rename(index={1:'first'}, columns={'item':'object'})
#특정 하나만 바꾸겠다

object   color  price
0         ball   white   5.56
first      mug     red   4.20
2          pen   green   1.30
3       pencil   black   0.56
4      ashtray  yellow   2.75

# 문제

In [366]:
df = pd.DataFrame(np.random.randint(10, size=(4, 4)), dtype=int)
df

0  1  2  3
0  0  9  5  3
1  7  3  1  0
2  2  1  6  6
3  4  8  9  1

In [378]:
df[df%2==0]=0
df

0  1  2  3
0  0  9  5  3
1  7  3  1  0
2  0  1  0  0
3  0  0  9  1

In [379]:
fruit_df = pd.DataFrame({ 'name':['apple','orange','melon','banana','mango']})
fruit_df

name
0   apple
1  orange
2   melon
3  banana
4   mango

In [388]:
prices = {
'apple' : 5.56,
'orange' : 4.20,
'melon' : 1.30,
'banana' : 3.41,
'mango' : 1.30,
}

In [389]:
fruit_df['price'] = fruit_df['name'].map(prices)
fruit_df

name  price
0   apple   5.56
1  orange   4.20
2   melon   1.30
3  banana   3.41
4   mango   1.30

In [390]:
fruit_df.replace({1.30:2500,3.41:3300})

name    price
0   apple     5.56
1  orange     4.20
2   melon  2500.00
3  banana  3300.00
4   mango  2500.00

In [391]:
reindex = {
0: 'A',
1: 'B',
2: 'C',
3: 'D',
4: 'E'}

In [393]:
fruit_df.rename(index=reindex, columns={'name':'furit_name','price':'furit_price'})

furit_name  furit_price
A      apple         5.56
B     orange         4.20
C      melon         1.30
D     banana         3.41
E      mango         1.30