In [6]:
#배열은 행열의 크기(방)을 미리 정해줘야 됨
import random
import numpy as np
a=np.zeros((2,3))

for row in range(2):
    for col in range(3):
        a[row][col] = random.randint(0,20)
a

array([[ 2., 10., 19.],
       [16.,  3.,  7.]])

In [2]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
rg=range(5) #range object로 리턴
for _ in rg:
    print(_, end=",")
    
list(rg)   

0,1,2,3,4,

[0, 1, 2, 3, 4]

In [7]:
np.arange(5) #배열의 범위(ndarray의 원소 범위)

array([0, 1, 2, 3, 4])

In [8]:
np.arange(3,6)

array([3, 4, 5])

In [10]:
a=np.arange(3,10,2) #3에서 10까지 2씩 뛰어넘기
type(a)

numpy.ndarray

In [11]:
np.arange(1,10,0.8)

array([1. , 1.8, 2.6, 3.4, 4.2, 5. , 5.8, 6.6, 7.4, 8.2, 9. , 9.8])

In [14]:
a=np.arange(0,12)

In [15]:
a.shape #행,열이 없으면 원소의 개수만 나옴

(12,)

In [20]:
b=a.reshape(3,4) #배열의 모양을 바꿈(모양을 다시 만들겠다)
#BUT 새롭게 만들어지는 것 원본은 바뀌지 않음
b#새로운 배열

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
b.shape

(3, 4)

In [18]:
a.shape #원본이 바뀌지 않음

(12,)

In [28]:
c=a.reshape(2,-1)#행이 정해지면 한 행에 들어가야 할 갯수는 이미 정해져 있음
#만약 계산하지 않는 다 하면 -1로 뒤에 열을 표현
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [29]:
#0-9 구간을 7개 수를 일정한 간격으로 추출, 선형으로  linearly spaced values

np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [31]:
np.linspace(0,10,5, endpoint=False)#0-10까지 일정한 간격으로 5개 가져오기
#endpoint false이면 마지막 수를 포함하지 않음  true라면 마지막 수 포함
#range와는 좀 다름

array([0., 2., 4., 6., 8.])

In [33]:
np.random.random((3,3))

array([[0.58254853, 0.32146459, 0.68217119],
       [0.94092024, 0.75278203, 0.246505  ],
       [0.97768592, 0.7290258 , 0.47757522]])

In [34]:
a= np.random.random(16).reshape((4,4))
a

array([[0.2103166 , 0.5345295 , 0.92860901, 0.55130298],
       [0.44456042, 0.76174034, 0.20129276, 0.13236466],
       [0.1444045 , 0.98881798, 0.56371997, 0.55147285],
       [0.48426021, 0.12305945, 0.73975579, 0.88684083]])

In [35]:
a.data

In [41]:
b=a.reshape(-1,8)#행수는 컴퓨터가 계산하고 열은16개
b.data

In [42]:
a*2

array([[0.42063321, 1.069059  , 1.85721801, 1.10260595],
       [0.88912085, 1.52348069, 0.40258552, 0.26472933],
       [0.28880901, 1.97763596, 1.12743994, 1.10294571],
       [0.96852042, 0.24611889, 1.47951159, 1.77368166]])

In [43]:
a+[1,1,1,1]

array([[1.2103166 , 1.5345295 , 1.92860901, 1.55130298],
       [1.44456042, 1.76174034, 1.20129276, 1.13236466],
       [1.1444045 , 1.98881798, 1.56371997, 1.55147285],
       [1.48426021, 1.12305945, 1.73975579, 1.88684083]])

In [44]:
np.sqrt(a) #universal function

array([[0.45860288, 0.73111524, 0.96364361, 0.7424978 ],
       [0.66675365, 0.87277737, 0.44865662, 0.36381955],
       [0.38000592, 0.99439327, 0.75081287, 0.74261218],
       [0.69588807, 0.3507983 , 0.86009057, 0.94172227]])

In [45]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [47]:
a.sum()

10

In [49]:
a.max(),a.min(),a.mean(),a.std() #mean은 평균, std는 표준편차

(4, 0, 2.0, 1.4142135623730951)

In [50]:
#분산:각 원소와 평균의 차이의 제곱, 이들을 모두 합산, 그값을 원소의 갯수로 나눔

In [52]:
np.sqrt(np.mean((a-a.mean())**2)), np.std(a)

(1.4142135623730951, 1.4142135623730951)

In [53]:
a= np.arange(1,17).reshape(4,-1)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [54]:
for e in a:
    for i in e:
        print(i, end=' ')
        

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 

In [56]:
a[1][2], a[1,2] #각행,열의 값을 가져옴 

(7, 7)

In [57]:
a[[1,2]]#1행과 2행을 가져옴

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
a[3,1]

14

In [60]:
a[[1,3]]


array([[ 5,  6,  7,  8],
       [13, 14, 15, 16]])

In [66]:
#fancy indexing :인덱서 안에 정수나 불리언 배열을 사용하여 배열의 값을 추출해내는 방법

ba=np.array([True,False,False,False,False,False,False,False,False,True,True,True,True,True])
ba= ba.reshape(2,-1)
ba

array([[ True, False, False, False, False, False, False],
       [False, False,  True,  True,  True,  True,  True]])

In [71]:
a[ba]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 4 but corresponding boolean dimension is 2

In [72]:
a[a<2]

array([1])

In [1]:
nums=[1,2,3,4,5]
nums[0:5]

[1, 2, 3, 4, 5]

In [2]:
nums[0:]

[1, 2, 3, 4, 5]

In [3]:
nums[:]

[1, 2, 3, 4, 5]

In [4]:
nums[::2]

[1, 3, 5]

In [5]:
nums[2]

3

In [7]:
a=np.arange(10,16)
a

array([10, 11, 12, 13, 14, 15])

In [8]:
a[1:5]

array([11, 12, 13, 14])

In [9]:
a[1:5:2]

array([11, 13])

In [13]:
a.data
b=a[::]
b.data

In [14]:
nums=list(range(5))
nums

[0, 1, 2, 3, 4]

In [18]:
nums2=nums[:]
nums2

[0, 1, 2, 3, 4]

In [19]:
nums2[0]=5
nums2

[5, 1, 2, 3, 4]

In [20]:
nums

[0, 1, 2, 3, 4]

In [21]:
a= np.arange(5)
a

array([0, 1, 2, 3, 4])

In [23]:
b=a[:]
b

array([0, 1, 2, 3, 4])

In [24]:
b[0]=5#array에서는 다른걸 바꿔도 원본이 바뀜
#리스트와는 다름
b

array([5, 1, 2, 3, 4])

In [25]:
a

array([5, 1, 2, 3, 4])

In [26]:
# 다차원 배열의 슬라이싱
#소문자로 하면 일차원, 이차원 배열은 대문자

In [29]:
A=np.arange(10,19).reshape(3,-1)
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [30]:
A[0,1:]#0번째 행 1번부터 다 그줄 다 가져 오기

array([11, 12])

In [31]:
A[0:2,1:]

array([[11, 12],
       [14, 15]])

In [45]:
A[:,0]#각 행의 맨 앞열만 가져오는 슬라이싱

array([10, 13, 16])

In [50]:
A[0,1:],A[2,1:]

(array([11, 12]), array([17, 18]))

In [51]:
A[::2,1:]

array([[11, 12],
       [17, 18]])

In [53]:
A[[0,2],1:]

array([[11, 12],
       [17, 18]])

In [56]:
for e in A:
    for a in e:
        print(a)

10
11
12
13
14
15
16
17
18


In [59]:
for n in A.flatten():
    print(n, end=' ')

10 11 12 13 14 15 16 17 18 

In [60]:
for n in A.ravel():
    print(n, end=' ')

10 11 12 13 14 15 16 17 18 

In [61]:
np.apply_along_axis(np.sum, axis=0,arr=A)#세로 합계

array([39, 42, 45])

In [71]:
a=np.zeros((4,4))

for row in range(4):
    for col in range(4):
        a[row][col] = random.randint(0,20)
print(a)     

np.apply_along_axis(np.max, axis=1,arr=a)#세로 합계        

[[ 5. 16. 20.  6.]
 [15. 17. 19. 11.]
 [20.  7.  1. 13.]
 [13. 10. 12. 17.]]


array([20., 19., 20., 17.])

In [73]:
lambda v:v-1

<function __main__.<lambda>(A)>

In [74]:
g=lambda v:v-1

g(A)

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [89]:
 add=0
for s in A.flatten():
    if s%2==1:
        add+=s
add     
      

56

array([[10, 11, 12],
       [16, 17, 18]])

In [131]:
S=A[A%2==1].sum()
S


56

In [136]:
A.data

In [137]:
A1=A.reshape(1,-1)
A1.data

In [139]:
A1.shape=(3,-1)
A1

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [140]:
A1.data

In [141]:
A1.shape=(9) #다차원에서 일차원으로
A1

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [142]:
A1.shape=(3,-1)
A1

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [144]:
A.transpose() #원채의 다차원 배열에서 각 행의 맨 첫열을 첫행, 그후 차례대로

array([[10, 13, 16],
       [11, 14, 17],
       [12, 15, 18]])

In [145]:
A=np.zeros((3,3))
B=np.ones((3,3))

In [147]:
np.vstack([A,B])#수직으로 쌓아라

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [148]:
np.hstack([A,B])#좌우 합치기

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [151]:
np.column_stack([[1,2,3],[4,5,6],[7,8,9]])#하나의 리스트를 하나의 컬럼으로(위에서 아래로)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [152]:
np.row_stack([[1,2,3],[4,5,6],[7,8,9]])#하나의 리스트를 하나의 행으로

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [153]:
A=np.arange(16).reshape(4,-1)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [160]:
A1,A2=np.hsplit(A,2)#좌우로 반
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [162]:
A1,A2=np.vsplit(A,2)#수직으로 반
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [176]:
np.split(A,[2,3], axis=0)#두번 짤라서 세개로 나누기

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

# Views, Copies

In [177]:
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [178]:
#cpoy는 복사한 것이므로 아무리 복사한것을 바꿔도 원본은 바뀌지 않음(다른 것)
#view는 객체의 주소는 같으나 참조변수만 다른것


In [180]:
b=a#주소가 같다(데이터가 복사된것이 아님)
b

array([1, 2, 3, 4])

In [182]:
c=a[0:2]#이것도 뷰
c

array([1, 2])

In [183]:
a[0]=5
c

array([5, 2])

In [184]:
a,c

(array([5, 2, 3, 4]), array([5, 2]))

In [185]:
c[1]=7
a

array([5, 7, 3, 4])

In [186]:
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [188]:
b=a.copy()#그냥 복사(원본은 그대로 남아있다, 객체의 주소도 다름) 
b

array([1, 2, 3, 4])

In [190]:
b[0]=5
b

array([5, 2, 3, 4])

In [191]:
a

array([1, 2, 3, 4])

In [192]:
a*2#broad casting

array([2, 4, 6, 8])

In [193]:
b

array([5, 2, 3, 4])

In [194]:
a*[2,1,5,6]

array([ 2,  2, 15, 24])

In [195]:
np.save('saved_ndarray',a)
print('파일의 저장 성공')

파일의 저장 성공


In [198]:
fa=np.load('saved_ndarray.npy')
fa

array([1, 2, 3, 4])

In [200]:
#csv(Comma Separated Values)
'''
id,value1,value2,value3
1,123,1.4,23
2,110,0.5,18
3,164,2.1,19'''


'\nid,value1,value2,value3\n1,123,1.4,23\n2,110,0.5,18\n3,164,2.1,19'

In [202]:
ta=np.genfromtxt('sample.csv',delimiter=',',names=True)

In [203]:
ta

array([(1., 123., 1.4, 23.), (2., 110., 0.5, 18.), (3., 164., 2.1, 19.)],
      dtype=[('id', '<f8'), ('value1', '<f8'), ('value2', '<f8'), ('value3', '<f8')])

In [205]:
ta[0][1]

123.0

In [206]:
ta.shape

(3,)

In [207]:
ta['id']#컬럽 id의 값을 전부 가져옴

array([1., 2., 3.])